version: '3.8'

services:
  norilsk_app:
    build: .
    restart: always
    volumes:
      - ./app/allowed_users.json:/app/allowed_users.json # Монтируем секреты
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Для SSL сертификатов
    depends_on:
      - norilsk_app