version: '3.8'

services:
  norilsk_app:
    build: .
    restart: always
    volumes:
      - ./app/allowed_users.json:/app/allowed_users.json
      - ./data:/data
      - ./templates:/templates
      - ./static:/static
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - norilsk_app